---
name: Redirect circleci artifacts
# Display a link to the artifacts at the bottom of a PR
# from https://github.com/marketplace/actions/run-circleci-artifacts-redirector
on: [status]
jobs:
    circleci_artifacts_redirector_job:
        runs-on: ubuntu-20.04
        name: Run CircleCI artifacts redirector
        steps:
        -   name: GitHub Action step
            uses: larsoner/circleci-artifacts-redirector-action@master
            with:
                repo-token: ${{ secrets.GITHUB_TOKEN }}
                artifact-path: 0/dev/index.html
                circleci-jobs: build_docs

    # circleci_artifacts_redirector_job:
    #     runs-on: ubuntu-latest
    #     if: "${{ startsWith(github.event.context, 'ci/circleci: build_docs_pdf') }}"
    #     permissions:
    #         statuses: write
    #     name: Run CircleCI artifacts redirector
    #     steps:
    #         -   name: GitHub Action step
    #             uses: larsoner/circleci-artifacts-redirector-action@master
    #             with:
    #                 repo-token: ${{ secrets.GITHUB_TOKEN }}
    #                 api-token: ${{ secrets.CIRCLECI_TOKEN }}
    #                 artifact-path: 0/dev/index.html
    #                 circleci-jobs: build_docs
    #                 job-title: Check the rendered doc here!
